//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.17 at 11:54:42 AM EST 
//


package command.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the command.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Commands_QNAME = new QName("", "commands");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: command.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link command.jaxb.CommandsType }
     * 
     */
    public CommandsType createCommandsType() {
        return new CommandsType();
    }

    /**
     * Create an instance of {@link command.jaxb.CommandType }
     * 
     */
    public CommandType createCommandType() {
        return new CommandType();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link command.jaxb.CommandsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "commands")
    public JAXBElement<CommandsType> createCommands(CommandsType value) {
        return new JAXBElement<CommandsType>(_Commands_QNAME, CommandsType.class, null, value);
    }

}
